### ISSUE TITLE
Radare Unavailable

### ISSUE THREAD

**Issue by surfer190** [radare/bokken#3] opened 2015-08-10 18:51 UTC
I can access `r2` from command line

but when running `./bokken` the dependency check says `Radare availability...   D'oh!`

**Comment by radare** [comment] 2015-08-10 18:54
how did you installed r2? which version of r2 are you running?

the dependency itself is not r2, but the companion libraries. iirc this test verifies that the bindings for python are working, so i guess the problem is that you havent installed the python bindings for radare2.

**Comment by surfer190** [comment] 2015-08-10 19:07
I cloned the r2 repo and ran `sys/install.sh` then `sys/python.sh`

**Comment by radare** [comment] 2015-08-11 09:01
then you didnt installed r2 in any custom directory

**Comment by surfer190** [comment] 2015-08-11 18:21
@radare ok

`which r2` gives `/usr/bin/r2`

Response of `sys/python.py` points to an error

```
do-swig.sh: 52: exec: valabind-cc: not found
... r_core.so
Build r_bin -lr_bin -lr_util -lr_db -lr_io  
valabind-cc python r_bin -NRadare -NSDB --swig -x --vapidir=../vapi ../vapi/r_bin -I/usr/include/libr -lr_bin -lr_util -lr_db -lr_io
do-swig.sh: 52: exec: valabind-cc: not found
... r_bin.so
Build r_asm -lr_asm -lr_util -lr_parse -lr_db -lr_syscall  
valabind-cc python r_asm -NRadare -NSDB --swig -x --vapidir=../vapi ../vapi/r_asm -I/usr/include/libr -lr_asm -lr_util -lr_parse -lr_db -lr_syscall
do-swig.sh: 52: exec: valabind-cc: not found
... r_asm.so
cd .. ; make install-python
make[1]: Entering directory `/home/stephen/utils/radare2/radare2-bindings'
test -f python/_r_core.so
make[1]: *** [install-python] Error 1
make[1]: Leaving directory `/home/stephen/utils/radare2/radare2-bindings'
make: *** [install] Error 2
```

**Comment by radare** [comment] 2015-08-11 18:43
you should install valabind from git or last release in order to build the bindings

**Comment by surfer190** [comment] 2015-08-11 20:07
I clone the repo and run 

```
./configure && make && make install
```

An error comes through:

```
configure: error: flex not found but required
```

**Comment by radare** [comment] 2015-08-11 22:23
Valabind diesnt requires flex. Which distro are you using? All this stuff should be already packaged

**Comment by BogusLogin** [comment] 2015-10-02 18:53
I suffer from the same problems, but I posted my issue to the [radare repo](https://github.com/radare/radare2/issues/3404)

**Comment by razaborg** [comment] 2017-10-27 21:20
Exact same problem for me, on macos.

I used `brew` to install both radare2 and bokken:

```
$ which radare2
/usr/local/bin/radare2
$ which bokken
/usr/local/bin/bokken
```

But when I want to start bokken, I just get the following error : 
```
Python version...	OK
Radare availability...	D'oh!
```
Could you tell me what Bokken uses to determine wether radare is "available" or not ?

**Comment by jaypikay** [comment] 2017-12-23 16:37
I also have the r2-bindings installed, but bokken fails to start. I looked up the import and tried myself

`$ python2 -c "import r2._r_core"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/python2.7/site-packages/r2/_r_core.so: undefined symbol: r_io_section_overlaps`

`$ objdump -R /usr/lib/python2.7/site-packages/r2/_r_core.so | grep r_io_section_overlaps
00000000003d9048 R_X86_64_JUMP_SLOT  r_io_section_overlaps`

**Comment by radare** [comment] 2017-12-24 09:22
The io api changed a lot. Probably bindings and broken are not ready for r2>=2.x

**Comment by radare** [comment] 2019-03-08 09:44
Closing the issue because the real repo for bokken is in https://github.com/inguma/bokken

**Closed by radare** 2019-03-08 09:44 UTC
